In [2]:
import numpy as np


In [3]:
#Question no.1
x = np.array([1,2,3])
N = 4
matrix = np.vander(x,N)
print(matrix)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]]


In [19]:
#Question no. 2
def moving_avg(a,k):
    cum = np.cumsum(a)
    cum[k:] = cum[k:]- cum[:-k]
    return cum[k-1:]/k
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
x= np.array(a)
np.array((moving_avg(x,3))).round(1)


array([  5. ,   4.7,   5.7,   6.7,   9.7,  28.7,  49.3,  72.7,  84. ,
        93.3, 116.3])